FROM wolferhua/php:7.1-fpm

MAINTAINER wolferhua

COPY  docker-php-entrypoint /usr/local/bin/

ENTRYPOINT ["docker-php-entrypoint"]

CMD ["php-fpm"]

#docker build -t wolferhua/php:7.1-fpm-root .








